-- Migration 046: UCL klubovy ciselnik - import z kluby_loga_staty.csv
-- Zdroj: sources/lm2026-27/kluby_loga_staty.csv

INSERT INTO "lm2026-27".teams (team_code, team_name, country_code, country_name, logo_file) VALUES
    ('ARSENAL', 'Arsenal', 'ENG', 'England', 'arsenal_logo.png'),
    ('ASTON_VILLA', 'Aston Villa', 'ENG', 'England', 'aston_villa_logo.png'),
    ('ATLETI', 'Atleti', 'ESP', 'Spain', 'atleti_logo.png'),
    ('B_DORTMUND', 'B. Dortmund', 'GER', 'Germany', 'b_dortmund_logo.png'),
    ('BARCELONA', 'Barcelona', 'ESP', 'Spain', 'barcelona_logo.png'),
    ('BAYERN_MNCHEN', 'Bayern München', 'GER', 'Germany', 'bayern_mnchen_logo.png'),
    ('CLUB_BRUGGE', 'Club Brugge', 'BEL', 'Belgium', 'club_brugge_logo.png'),
    ('COMO', 'Como', 'ITA', 'Italy', 'como_logo.png'),
    ('FEYENOORD', 'Feyenoord', 'NED', 'Netherlands', 'feyenoord_logo.png'),
    ('GALATASARAY', 'Galatasaray', 'TUR', 'Turkey', 'galatasaray_logo.png'),
    ('INTER', 'Inter', 'ITA', 'Italy', 'inter_logo.png'),
    ('LEIPZIG', 'Leipzig', 'GER', 'Germany', 'leipzig_logo.png'),
    ('LENS', 'Lens', 'FRA', 'France', 'lens_logo.png'),
    ('LILLE', 'Lille', 'FRA', 'France', 'lille_logo.png'),
    ('LIVERPOOL', 'Liverpool', 'ENG', 'England', 'liverpool_logo.png'),
    ('MAN_CITY', 'Man City', 'ENG', 'England', 'man_city_logo.png'),
    ('MAN_UTD', 'Man Utd', 'ENG', 'England', 'man_utd_logo.png'),
    ('NAPOLI', 'Napoli', 'ITA', 'Italy', 'napoli_logo.png'),
    ('PARIS', 'Paris', 'FRA', 'France', 'paris_logo.png'),
    ('PORTO', 'Porto', 'POR', 'Portugal', 'porto_logo.png'),
    ('PSV', 'PSV', 'NED', 'Netherlands', 'psv_logo.png'),
    ('REAL_BETIS', 'Real Betis', 'ESP', 'Spain', 'real_betis_logo.png'),
    ('REAL_MADRID', 'Real Madrid', 'ESP', 'Spain', 'real_madrid_logo.png'),
    ('ROMA', 'Roma', 'ITA', 'Italy', 'roma_logo.png'),
    ('SHAKHTAR', 'Shakhtar', 'UKR', 'Ukraine', 'shakhtar_logo.png'),
    ('SLAVIA_PRAHA', 'Slavia Praha', 'CZE', 'Czechia', 'slavia_praha_logo.png'),
    ('SPORTING_CP', 'Sporting CP', 'POR', 'Portugal', 'sporting_cp_logo.png'),
    ('STUTTGART', 'Stuttgart', 'GER', 'Germany', 'stuttgart_logo.png'),
    ('VILLARREAL', 'Villarreal', 'ESP', 'Spain', 'villarreal_logo.png'),
    ('AEK_ATHENS', 'AEK Athens', 'GRE', 'Greece', 'aek_athens_logo.png'),
    ('CELTIC', 'Celtic', 'SCO', 'Scotland', 'celtic_logo.png'),
    ('LASK', 'LASK', 'AUT', 'Austria', 'lask_logo.png'),
    ('VIKING', 'Viking', 'NOR', 'Norway', 'viking_logo.png'),
    ('BODGLIMT', 'Bodø/Glimt', 'NOR', 'Norway', 'bodglimt_logo.png'),
    ('LYON', 'Lyon', 'FRA', 'France', 'lyon_logo.png'),
    ('NEC', 'N.E.C.', 'NED', 'Netherlands', 'nec_logo.png'),
    ('OLYMPIACOS', 'Olympiacos', 'GRE', 'Greece', 'olympiacos_logo.png'),
    ('SPARTA_PRAHA', 'Sparta Praha', 'CZE', 'Czechia', 'sparta_praha_logo.png'),
    ('UNION_SG', 'Union SG', 'BEL', 'Belgium', 'union_sg_logo.png'),
    ('AARHUS', 'Aarhus', 'DEN', 'Denmark', 'aarhus_logo.png'),
    ('ARARAT_ARMENIA', 'Ararat-Armenia', 'ARM', 'ARM', 'ararat_armenia_logo.png'),
    ('CELJE', 'Celje', 'SVN', 'SVN', 'celje_logo.png'),
    ('CRVENA_ZVEZDA', 'Crvena Zvezda', 'SRB', 'Serbia', 'crvena_zvezda_logo.png'),
    ('EGNATIA', 'Egnatia', 'ALB', 'ALB', 'egnatia_logo.png'),
    ('FENERBAHE', 'Fenerbahçe', 'TUR', 'Turkey', 'fenerbahe_logo.png'),
    ('GNK_DINAMO', 'GNK Dinamo', 'CRO', 'Croatia', 'gnk_dinamo_logo.png'),
    ('GRNIK_ZABRZE', 'Górnik Zabrze', 'POL', 'Poland', 'grnik_zabrze_logo.png'),
    ('H_BEER_SHEVA', 'H. Beer-Sheva', 'ISR', 'Israel', 'h_beer_sheva_logo.png'),
    ('HEARTS', 'Hearts', 'SCO', 'Scotland', 'hearts_logo.png'),
    ('IBERIA_TBILISI', 'Iberia Tbilisi', 'GEO', 'GEO', 'iberia_tbilisi_logo.png'),
    ('KAIRAT_ALMATY', 'Kairat Almaty', 'KAZ', 'Kazakhstan', 'kairat_almaty_logo.png'),
    ('KAUNO_ALGIRIS', 'Kauno Žalgiris', 'LTU', 'LTU', 'kauno_algiris_logo.png'),
    ('KLAKSVK', 'Klaksvík', 'FRO', 'FRO', 'klaksvk_logo.png'),
    ('KUPS_KUOPIO', 'KuPS Kuopio', 'FIN', 'Finland', 'kups_kuopio_logo.png'),
    ('L_RED_IMPS', 'L. Red Imps', 'GIB', 'GIB', 'l_red_imps_logo.png'),
    ('LARNE', 'Larne', 'NIR', 'NIR', 'larne_logo.png'),
    ('LECH_POZNA', 'Lech Poznań', 'POL', 'Poland', 'lech_pozna_logo.png'),
    ('LEVSKI_SOFIA', 'Levski Sofia', 'BUL', 'Bulgaria', 'levski_sofia_logo.png'),
    ('MJLLBY', 'Mjällby', 'SWE', 'Sweden', 'mjllby_logo.png'),
    ('OMONIA', 'Omonia', 'CYP', 'Cyprus', 'omonia_logo.png'),
    ('S_BRATISLAVA', 'S. Bratislava', 'SVK', 'Slovakia', 's_bratislava_logo.png'),
    ('SABAH', 'Sabah', 'AZE', 'Azerbaijan', 'sabah_logo.png'),
    ('SHAMROCK_ROVERS', 'Shamrock Rovers', 'IRL', 'IRL', 'shamrock_rovers_logo.png'),
    ('STURM_GRAZ', 'Sturm Graz', 'AUT', 'Austria', 'sturm_graz_logo.png'),
    ('THUN', 'Thun', 'SUI', 'Switzerland', 'thun_logo.png'),
    ('U_CRAIOVA', 'U. Craiova', 'ROU', 'Romania', 'u_craiova_logo.png'),
    ('VKINGUR_R', 'Víkingur R.', 'ISL', 'ISL', 'vkingur_r_logo.png'),
    ('ATERT_BISSEN', 'Atert Bissen', 'LUX', 'LUX', 'atert_bissen_logo.png'),
    ('BORAC', 'Borac', 'BIH', 'BIH', 'borac_logo.png'),
    ('DRITA', 'Drita', 'KOS', 'KOS', 'drita_logo.png'),
    ('FLORA_TALLINN', 'Flora Tallinn', 'EST', 'EST', 'flora_tallinn_logo.png'),
    ('FLORIANA', 'Floriana', 'MLT', 'MLT', 'floriana_logo.png'),
    ('GYRI_ETO', 'Győri ETO', 'HUN', 'Hungary', 'gyri_eto_logo.png'),
    ('INTER_ESCALDES', 'Inter Escaldes', 'AND', 'AND', 'inter_escaldes_logo.png'),
    ('ML_VITEBSK', 'ML Vitebsk', 'BLR', 'BLR', 'ml_vitebsk_logo.png'),
    ('PETROCUB', 'Petrocub', 'MDA', 'Moldova', 'petrocub_logo.png'),
    ('RIGA', 'Riga', 'LVA', 'LVA', 'riga_logo.png'),
    ('SUTJESKA', 'Sutjeska', 'MNE', 'MNE', 'sutjeska_logo.png'),
    ('THE_NEW_SAINTS', 'The New Saints', 'WAL', 'Wales', 'the_new_saints_logo.png'),
    ('TRE_FIORI', 'Tre Fiori', 'SMR', 'SMR', 'tre_fiori_logo.png'),
    ('VARDAR', 'Vardar', 'MKD', 'MKD', 'vardar_logo.png')
ON CONFLICT (team_code) DO UPDATE SET team_name = EXCLUDED.team_name, country_code = EXCLUDED.country_code, country_name = EXCLUDED.country_name, logo_file = EXCLUDED.logo_file;

INSERT INTO admin.schema_versions (version, description)
VALUES (46, 'UCL import klubov z CSV: nazov, stat, kod statu a logo')
ON CONFLICT (version) DO NOTHING;
