-- Migration 054: naplnenie ciselnika statov zo zdrojoveho CSV
-- Zdroj: sources/flags/state_flag_list.csv (254 statov), vlajky v sources/flags/
--
-- Ciselnik sa najprv vyprazdni, preto sa UCL kluby docasne odpoja od FK
-- a po importe znova napoja cez sportove kody UEFA.
-- Cela migracia bezi v jednej transakcii: pri chybe sa nic nezmeni.
--
-- V CSV je "-" znacka pre chybajucu hodnotu a uklada sa ako NULL.
-- Ak stat nema anglicky nazov, pouzije sa slovensky (name_en je NOT NULL).

BEGIN;

-- 1. Odpojit kluby od oboch ciselnikov, aby sa dali vyprazdnit.
--    Na teams.country_code su dva FK: z migracie 048 na stary "lm2026-27".countries
--    a z migracie 050 na admin.countries. Oba musia prec, inak stary FK zablokuje
--    ISO kody, ktore v starej tabulke nie su (napr. GB-ENG).
ALTER TABLE "lm2026-27".teams DROP CONSTRAINT IF EXISTS ucl_teams_admin_country_code_fkey;
ALTER TABLE "lm2026-27".teams DROP CONSTRAINT IF EXISTS ucl_teams_country_code_fkey;

-- 2. Vyprazdnit ciselnik.
DELETE FROM admin.countries;

-- 3. Nahrat staty z CSV.
INSERT INTO admin.countries
    (source_id, country_code, country_code2, name_sk, name_en, name_original,
     name_sk_long, flag_file, flag_file_big, flag_check)
VALUES
    (1, 'AFG', 'AF', 'Afganistan', 'Afghanistan', NULL, 'Afganská islamská republika', 'flag_af_24.png', 'flag_af_240.png', 'OK'),
    (2, 'ALA', 'AX', 'Alandy', 'Alandy', NULL, 'Alandské ostrovy', 'flag_ax_24.png', 'flag_ax_240.png', 'OK'),
    (3, 'ALB', 'AL', 'Albánsko', 'Albania', NULL, 'Albánska republika', 'flag_al_24.png', 'flag_al_240.png', 'OK'),
    (4, 'DZA', 'DZ', 'Alžírsko', 'Algeria', NULL, 'Alžírska demokratická ľudová republika', 'flag_dz_24.png', 'flag_dz_240.png', 'OK'),
    (5, 'ASM', 'AS', 'Americká Samoa', 'Americká Samoa', NULL, 'Americká Samoa', 'flag_as_24.png', 'flag_as_240.png', 'OK'),
    (6, 'VIR', 'VI', 'Americké Panenské ostrovy', 'Americké Panenské ostrovy', NULL, 'Americké Panenské ostrovy', 'flag_vi_24.png', 'flag_vi_240.png', 'OK'),
    (7, 'AND', 'AD', 'Andorra', 'Andorra', NULL, 'Andorrské kniežatstvo', 'flag_ad_24.png', 'flag_ad_240.png', 'OK'),
    (8, 'GB-ENG', 'GB-ENG', 'Anglicko', 'England', NULL, 'Anglicko', 'flag_gb-eng_24.png', 'flag_gb-eng_240.png', 'OK'),
    (9, 'AGO', 'AO', 'Angola', 'Angola', NULL, 'Angolská republika', 'flag_ao_24.png', 'flag_ao_240.png', 'OK'),
    (10, 'AIA', 'AI', 'Anguilla', 'Anguilla', NULL, 'Anguilla', 'flag_ai_24.png', 'flag_ai_240.png', 'OK'),
    (11, 'ATA', 'AQ', 'Antarktída', 'Antarktída', NULL, 'Antarktída', 'flag_aq_24.png', 'flag_aq_240.png', 'OK'),
    (12, 'ATG', 'AG', 'Antigua a Barbuda', 'Antigua a Barbuda', NULL, 'Antigua a Barbuda', 'flag_ag_24.png', 'flag_ag_240.png', 'OK'),
    (13, 'ARG', 'AR', 'Argentína', 'Argentina', NULL, 'Argentínska republika', 'flag_ar_24.png', 'flag_ar_240.png', 'OK'),
    (14, 'ARM', 'AM', 'Arménsko', 'Arménsko', NULL, 'Arménska republika', 'flag_am_24.png', 'flag_am_240.png', 'OK'),
    (15, 'ABW', 'AW', 'Aruba', 'Aruba', NULL, 'Aruba', 'flag_aw_24.png', 'flag_aw_240.png', 'OK'),
    (16, 'AUS', 'AU', 'Austrália', 'Australia', NULL, 'Austrálsky zväz', 'flag_au_24.png', 'flag_au_240.png', 'OK'),
    (17, 'AZE', 'AZ', 'Azerbajdžan', 'Azerbajdžan', NULL, 'Azerbajǆanská republika', 'flag_az_24.png', 'flag_az_240.png', 'OK'),
    (18, 'BHS', 'BS', 'Bahamy', 'Bahamy', NULL, 'Bahamské spoločenstvo', 'flag_bs_24.png', 'flag_bs_240.png', 'OK'),
    (19, 'BHR', 'BH', 'Bahrajn', 'Bahrajn', NULL, 'Bahrajnské kráľovstvo', 'flag_bh_24.png', 'flag_bh_240.png', 'OK'),
    (20, 'BGD', 'BD', 'Bangladéš', 'Bangladesh', NULL, 'Bangladéšska ľudová republika', 'flag_bd_24.png', 'flag_bd_240.png', 'OK'),
    (21, 'BRB', 'BB', 'Barbados', 'Barbados', NULL, 'Barbados', 'flag_bb_24.png', 'flag_bb_240.png', 'OK'),
    (22, 'BEL', 'BE', 'Belgicko', 'Belgium', NULL, 'Belgické kráľovstvo', 'flag_be_24.png', 'flag_be_240.png', 'OK'),
    (23, 'BLZ', 'BZ', 'Belize', 'Belize', NULL, 'Belize', 'flag_bz_24.png', 'flag_bz_240.png', 'OK'),
    (24, 'BEN', 'BJ', 'Benin', 'Benin', NULL, 'Beninská republika', 'flag_bj_24.png', 'flag_bj_240.png', 'OK'),
    (25, 'BMU', 'BM', 'Bermudy', 'Bermudy', NULL, 'Bermudy', 'flag_bm_24.png', 'flag_bm_240.png', 'OK'),
    (26, 'BTN', 'BT', 'Bhután', 'Bhután', NULL, 'Bhutánske krâľovstvo', 'flag_bt_24.png', 'flag_bt_240.png', 'OK'),
    (27, 'BLR', 'BY', 'Bielorusko', 'Belarus', NULL, 'Bieloruská republika', 'flag_by_24.png', 'flag_by_240.png', 'OK'),
    (28, 'BOL', 'BO', 'Bolívia', 'Bolivia', NULL, 'Bolívijská republika', 'flag_bo_24.png', 'flag_bo_240.png', 'OK'),
    (29, 'BES', 'BQ', 'Bonaire, Sint Eustatius a Saba', 'Bonaire, Sint Eustatius a Saba', NULL, 'Bonaire, Sint Eustatius a Saba', 'flag_bq_24.png', 'flag_bq_240.png', 'OK'),
    (30, 'BIH', 'BA', 'Bosna a Hercegovina', 'Bosna a Hercegovina', NULL, 'Republika Bosny a Hercegoviny', 'flag_ba_24.png', 'flag_ba_240.png', 'OK'),
    (31, 'BWA', 'BW', 'Botswana', 'Botswana', NULL, 'Botswanská republika', 'flag_bw_24.png', 'flag_bw_240.png', 'OK'),
    (32, 'BVT', 'BV', 'Bouvetov ostrov', 'Bouvetov ostrov', NULL, 'Bouvetov ostrov', 'flag_bv_24.png', 'flag_bv_240.png', 'OK'),
    (33, 'BRA', 'BR', 'Brazília', 'Brazil', NULL, 'Brazílska federatívna republika', 'flag_br_24.png', 'flag_br_240.png', 'OK'),
    (34, 'IOT', 'IO', 'Britské indickooceánske územie', 'Britské indickooceánske územie', NULL, 'Britské indickooceánske územie', 'flag_io_24.png', 'flag_io_240.png', 'OK'),
    (35, 'BRN', 'BN', 'Brunej', 'Brunej', NULL, 'Brunejský sultanât', 'flag_bn_24.png', 'flag_bn_240.png', 'OK'),
    (36, 'BGR', 'BG', 'Bulharsko', 'Bulgaria', NULL, 'Bulharská republika', 'flag_bg_24.png', 'flag_bg_240.png', 'OK'),
    (37, 'BFA', 'BF', 'Burkina Faso', 'Burkina Faso', NULL, 'Burkina Faso', 'flag_bf_24.png', 'flag_bf_240.png', 'OK'),
    (38, 'BDI', 'BI', 'Burundi', 'Burundi', NULL, 'Burundská republika', 'flag_bi_24.png', 'flag_bi_240.png', 'OK'),
    (39, 'COK', 'CK', 'Cookove ostrovy', 'Cookove ostrovy', NULL, 'Cookove ostrovy', 'flag_ck_24.png', 'flag_ck_240.png', 'OK'),
    (40, 'CUW', 'CW', 'Curacao', 'Curacao', NULL, 'Curacao', 'flag_cw_24.png', 'flag_cw_240.png', 'OK'),
    (41, 'CYP', 'CY', 'Cyprus', 'Cyprus', NULL, 'Cyperská republika', 'flag_cy_24.png', 'flag_cy_240.png', 'OK'),
    (42, 'TCD', 'TD', 'Čad', 'Čad', NULL, 'Čadská republika', 'flag_td_24.png', 'flag_td_240.png', 'OK'),
    (43, 'CZE', 'CZ', 'Česko', 'Czech Republic', NULL, 'Česká republika', 'flag_cz_24.png', 'flag_cz_240.png', 'OK'),
    (44, 'MNE', 'ME', 'Čierna Hora', 'Čierna Hora', NULL, 'Čierna Hora', 'flag_me_24.png', 'flag_me_240.png', 'OK'),
    (45, 'CHL', 'CL', 'Čile', 'Chile', NULL, 'Čílska republika', 'flag_cl_24.png', 'flag_cl_240.png', 'OK'),
    (46, 'CHN', 'CN', 'Čína', 'China', NULL, 'Čínska ľudová republika', 'flag_cn_24.png', 'flag_cn_240.png', 'OK'),
    (47, 'DNK', 'DK', 'Dánsko', 'Denmark', NULL, 'Dánske kráľovstvo', 'flag_dk_24.png', 'flag_dk_240.png', 'OK'),
    (48, 'DMA', 'DM', 'Dominika', 'Dominika', NULL, 'Dominické spoločenstvo', 'flag_dm_24.png', 'flag_dm_240.png', 'OK'),
    (49, 'DOM', 'DO', 'Dominikánska republika', 'Dominikánska republika', NULL, 'Dominikánska republika', 'flag_do_24.png', 'flag_do_240.png', 'OK'),
    (50, 'DJI', 'DJ', 'Džibutsko', 'Džibutsko', NULL, 'ǅibutská republika', 'flag_dj_24.png', 'flag_dj_240.png', 'OK'),
    (51, 'EGY', 'EG', 'Egypt', 'Egypt', NULL, 'Egyptská arabská republika', 'flag_eg_24.png', 'flag_eg_240.png', 'OK'),
    (52, 'ECU', 'EC', 'Ekvádor', 'Ecuador', NULL, 'Ekvádorská republika', 'flag_ec_24.png', 'flag_ec_240.png', 'OK'),
    (53, 'ERI', 'ER', 'Eritrea', 'Eritrea', NULL, 'Eritrejský štát', 'flag_er_24.png', 'flag_er_240.png', 'OK'),
    (54, 'EST', 'EE', 'Estónsko', 'Estonia', NULL, 'Estónska republika', 'flag_ee_24.png', 'flag_ee_240.png', 'OK'),
    (55, 'ETH', 'ET', 'Etiópia', 'Ethiopia', NULL, 'Etiópska federatívna demokratická republika', 'flag_et_24.png', 'flag_et_240.png', 'OK'),
    (56, 'FRO', 'FO', 'Faerské ostrovy', 'Faerské ostrovy', NULL, 'Faerské ostrovy', 'flag_fo_24.png', 'flag_fo_240.png', 'OK'),
    (57, 'FLK', 'FK', 'Falklandy', 'Falklandy', NULL, 'Falklandské ostrovy', 'flag_fk_24.png', 'flag_fk_240.png', 'OK'),
    (58, 'FJI', 'FJ', 'Fidži', 'Fiji', NULL, 'Fiǆijská republika', 'flag_fj_24.png', 'flag_fj_240.png', 'OK'),
    (59, 'PHL', 'PH', 'Filipíny', 'Philippines', NULL, 'Filipínska republika', 'flag_ph_24.png', 'flag_ph_240.png', 'OK'),
    (60, 'FIN', 'FI', 'Fínsko', 'Finland', NULL, 'Fínska republika', 'flag_fi_24.png', 'flag_fi_240.png', 'OK'),
    (61, 'PYF', 'PF', 'Francúzska Polynézia', 'Francúzska Polynézia', NULL, 'Francúzska Polynézia', 'flag_pf_24.png', 'flag_pf_240.png', 'OK'),
    (62, 'ATF', 'TF', 'Francúzske južné a antarktické územia', 'Francúzske južné a antarktické územia', NULL, 'Francúzske južné a antarktické územia', 'flag_tf_24.png', 'flag_tf_240.png', 'OK'),
    (63, 'FRA', 'FR', 'Francúzsko', 'France', NULL, 'Francúzska republika', 'flag_fr_24.png', 'flag_fr_240.png', 'OK'),
    (64, 'GAB', 'GA', 'Gabon', 'Gabon', NULL, 'Gabonská republika', 'flag_ga_24.png', 'flag_ga_240.png', 'OK'),
    (65, 'GMB', 'GM', 'Gambia', 'Gambia', NULL, 'Gambijská republika', 'flag_gm_24.png', 'flag_gm_240.png', 'OK'),
    (66, 'GHA', 'GH', 'Ghana', 'Ghana', NULL, 'Ghanská republika', 'flag_gh_24.png', 'flag_gh_240.png', 'OK'),
    (67, 'GIB', 'GI', 'Gibraltár', 'Gibraltár', NULL, 'Gibraltár', 'flag_gi_24.png', 'flag_gi_240.png', 'OK'),
    (68, 'GRC', 'GR', 'Grécko', 'Greece', NULL, 'Grécka republika', 'flag_gr_24.png', 'flag_gr_240.png', 'OK'),
    (69, 'GRD', 'GD', 'Grenada', 'Grenada', NULL, 'Grenada', 'flag_gd_24.png', 'flag_gd_240.png', 'OK'),
    (70, 'GRL', 'GL', 'Grónsko', 'Grónsko', NULL, 'Grónsko', 'flag_gl_24.png', 'flag_gl_240.png', 'OK'),
    (71, 'GEO', 'GE', 'Gruzínsko', 'Georgia', NULL, 'Gruzínsko', 'flag_ge_24.png', 'flag_ge_240.png', 'OK'),
    (72, 'GLP', 'GP', 'Guadeloupe', 'Guadeloupe', NULL, 'Guadeloupe', 'flag_gp_24.png', 'flag_gp_240.png', 'OK'),
    (73, 'GUM', 'GU', 'Guam', 'Guam', NULL, 'Guam', 'flag_gu_24.png', 'flag_gu_240.png', 'OK'),
    (74, 'GTM', 'GT', 'Guatemala', 'Guatemala', NULL, 'Guatemalská republika', 'flag_gt_24.png', 'flag_gt_240.png', 'OK'),
    (75, 'GGY', 'GG', 'Guernsey', 'Guernsey', NULL, 'Guernsey', 'flag_gg_24.png', 'flag_gg_240.png', 'OK'),
    (76, 'GIN', 'GN', 'Guinea', 'Guinea', NULL, 'Guinejská republika', 'flag_gn_24.png', 'flag_gn_240.png', 'OK'),
    (77, 'GNB', 'GW', 'Guinea-Bissau', 'Guinea-Bissau', NULL, 'Guinejsko-bissauská republika', 'flag_gw_24.png', 'flag_gw_240.png', 'OK'),
    (78, 'GUF', 'GF', 'Francúzska Guyana', 'Francúzska Guyana', NULL, 'Francúzska Guyana', 'flag_gf_24.png', 'flag_gf_240.png', 'OK'),
    (79, 'GUY', 'GY', 'Guyana', 'Guyana', NULL, 'Guyanská kooperatívna republika', 'flag_gy_24.png', 'flag_gy_240.png', 'OK'),
    (80, 'HTI', 'HT', 'Haiti', 'Haiti', NULL, 'Haitská republika', 'flag_ht_24.png', 'flag_ht_240.png', 'OK'),
    (81, 'HMD', 'HM', 'Heardov ostrov', 'Heardov ostrov', NULL, 'Teritórium Heardovho ostrova a Macdonaldových ostrovov', 'flag_hm_24.png', 'flag_hm_240.png', 'OK'),
    (82, 'NLD', 'NL', 'Holandsko', 'Netherlands', NULL, 'Holandské kráľovstvo', 'flag_nl_24.png', 'flag_nl_240.png', 'OK'),
    (83, 'HND', 'HN', 'Honduras', 'Honduras', NULL, 'Honduraská republika', 'flag_hn_24.png', 'flag_hn_240.png', 'OK'),
    (84, 'HKG', 'HK', 'Hongkong', 'Hongkong', NULL, 'Špeciálna administratívna oblasťČínskej ľudovej republiky Hongkong', 'flag_hk_24.png', 'flag_hk_240.png', 'OK'),
    (85, 'HRV', 'HR', 'Chorvátsko', 'Croatia', NULL, 'Chorvátska republika', 'flag_hr_24.png', 'flag_hr_240.png', 'OK'),
    (86, 'IND', 'IN', 'India', 'India', NULL, 'Indická republika', 'flag_in_24.png', 'flag_in_240.png', 'OK'),
    (87, 'IDN', 'ID', 'Indonézia', 'Indonesia', NULL, 'Indonézska republika', 'flag_id_24.png', 'flag_id_240.png', 'OK'),
    (88, 'IRQ', 'IQ', 'Irak', 'Iraq', NULL, 'Iracká republika', 'flag_iq_24.png', 'flag_iq_240.png', 'OK'),
    (89, 'IRN', 'IR', 'Irán', 'Iran', NULL, 'Iránska islamská republika', 'flag_ir_24.png', 'flag_ir_240.png', 'OK'),
    (90, 'IRL', 'IE', 'Írsko', 'Ireland', NULL, 'Írska republika', 'flag_ie_24.png', 'flag_ie_240.png', 'OK'),
    (91, 'ISL', 'IS', 'Island', 'Iceland', NULL, 'Islandská republika', 'flag_is_24.png', 'flag_is_240.png', 'OK'),
    (92, 'ISR', 'IL', 'Izrael', 'Israel', NULL, 'Izraelský štát', 'flag_il_24.png', 'flag_il_240.png', 'OK'),
    (93, 'JAM', 'JM', 'Jamajka', 'Jamaica', NULL, 'Jamajka', 'flag_jm_24.png', 'flag_jm_240.png', 'OK'),
    (94, 'JPN', 'JP', 'Japonsko', 'Japan', NULL, 'Japonsko', 'flag_jp_24.png', 'flag_jp_240.png', 'OK'),
    (95, 'YEM', 'YE', 'Jemen', 'Yemen', NULL, 'Jemenská republika', 'flag_ye_24.png', 'flag_ye_240.png', 'OK'),
    (96, 'JEY', 'JE', 'Jersey', 'Jersey', NULL, 'Bailiwick Jersey', 'flag_je_24.png', 'flag_je_240.png', 'OK'),
    (97, 'JOR', 'JO', 'Jordánsko', 'Jordan', NULL, 'Jordánske hášimovské kráľovstvo', 'flag_jo_24.png', 'flag_jo_240.png', 'OK'),
    (98, 'ZAF', 'ZA', 'Juhoafrická republika', 'South Africa', NULL, 'Juhoafrická republika', 'flag_za_24.png', 'flag_za_240.png', 'OK'),
    (99, 'SGS', 'GS', 'Južná Georgia a Južné Sandwichove ostrovy', 'Južná Georgia a Južné Sandwichove ostrovy', NULL, 'Južná Georgia a Južné Sandwichove ostrovy', 'flag_gs_24.png', 'flag_gs_240.png', 'OK'),
    (100, 'KOR', 'KR', 'Kórejská republika', 'South Korea', NULL, 'Kórejská republika', 'flag_kr_24.png', 'flag_kr_240.png', 'OK'),
    (101, 'SSD', 'SS', 'Južný Sudán', 'Južný Sudán', NULL, 'Juhosudánska republika', 'flag_ss_24.png', 'flag_ss_240.png', 'OK'),
    (102, 'CYM', 'KY', 'Kajmanie ostrovy', 'Kajmanie ostrovy', NULL, 'Kajmanie ostrovy', 'flag_ky_24.png', 'flag_ky_240.png', 'OK'),
    (103, 'KHM', 'KH', 'Kambodža', 'Cambodia', NULL, 'Kamboǆské kráľovstvo', 'flag_kh_24.png', 'flag_kh_240.png', 'OK'),
    (104, 'CMR', 'CM', 'Kamerun', 'Kamerun', NULL, 'Kamerunská republika', 'flag_cm_24.png', 'flag_cm_240.png', 'OK'),
    (105, 'CAN', 'CA', 'Kanada', 'Canada', NULL, 'Kanada', 'flag_ca_24.png', 'flag_ca_240.png', 'OK'),
    (106, 'CPV', 'CV', 'Kapverdy', 'Kapverdy', NULL, 'Kapverdská republika', 'flag_cv_24.png', 'flag_cv_240.png', 'OK'),
    (107, 'QAT', 'QA', 'Katar', 'Katar', NULL, 'Katarský štát', 'flag_qa_24.png', 'flag_qa_240.png', 'OK'),
    (108, 'KAZ', 'KZ', 'Kazachstan', 'Kazakhstan', NULL, 'Kazašská republika', 'flag_kz_24.png', 'flag_kz_240.png', 'OK'),
    (109, 'KEN', 'KE', 'Keňa', 'Kenya', NULL, 'Kenská republika', 'flag_ke_24.png', 'flag_ke_240.png', 'OK'),
    (110, 'KGZ', 'KG', 'Kirgizsko', 'Kirgizsko', NULL, 'Kirgizská republika', 'flag_kg_24.png', 'flag_kg_240.png', 'OK'),
    (111, 'KIR', 'KI', 'Kiribati', 'Kiribati', NULL, 'Kiribatská republika', 'flag_ki_24.png', 'flag_ki_240.png', 'OK'),
    (112, 'CCK', 'CC', 'Kokosové ostrovy', 'Kokosové ostrovy', NULL, 'Kokosové ostrovy', 'flag_cc_24.png', 'flag_cc_240.png', 'OK'),
    (113, 'COL', 'CO', 'Kolumbia', 'Colombia', NULL, 'Kolumbijská republika', 'flag_co_24.png', 'flag_co_240.png', 'OK'),
    (114, 'COM', 'KM', 'Komory', 'Komory', NULL, 'Komorská únia', 'flag_km_24.png', 'flag_km_240.png', 'OK'),
    (115, 'COD', 'CD', 'DR Kongo', 'Democratic Republic of the Congo', NULL, 'Konžská demokratická republika', 'flag_cd_24.png', 'flag_cd_240.png', 'OK'),
    (116, 'COG', 'CG', 'Kongo', 'Kongo', NULL, 'Konžská republika', 'flag_cg_24.png', 'flag_cg_240.png', 'OK'),
    (117, 'PRK', 'KP', 'Kórejská ľudovodemokratická republika', 'North Korea', NULL, 'Kórejská ľudovodemokratická republika', 'flag_kp_24.png', 'flag_kp_240.png', 'OK'),
    (118, 'UNK', 'XK', 'Kosovo', 'Kosovo', NULL, 'Republika Kosovo', 'flag_xk_24.png', 'flag_xk_240.png', 'OK'),
    (119, 'CRI', 'CR', 'Kostarika', 'Kostarika', NULL, 'Kostarická republika', 'flag_cr_24.png', 'flag_cr_240.png', 'OK'),
    (120, 'CUB', 'CU', 'Kuba', 'Cuba', NULL, 'Kubánska republika', 'flag_cu_24.png', 'flag_cu_240.png', 'OK'),
    (121, 'KWT', 'KW', 'Kuvajt', 'Kuwait', NULL, 'Kuvajtský štát', 'flag_kw_24.png', 'flag_kw_240.png', 'OK'),
    (122, 'LAO', 'LA', 'Laos', 'Laos', NULL, 'Laoská ľudovodemokratická republika', 'flag_la_24.png', 'flag_la_240.png', 'OK'),
    (123, 'LSO', 'LS', 'Lesotho', 'Lesotho', NULL, 'Lesothské kráľovstvo', 'flag_ls_24.png', 'flag_ls_240.png', 'OK'),
    (124, 'LBN', 'LB', 'Libanon', 'Lebanon', NULL, 'Libanonská republika', 'flag_lb_24.png', 'flag_lb_240.png', 'OK'),
    (125, 'LBR', 'LR', 'Libéria', 'Libéria', NULL, 'Libérijská republika', 'flag_lr_24.png', 'flag_lr_240.png', 'OK'),
    (126, 'LBY', 'LY', 'Líbya', 'Libya', NULL, 'Líbya', 'flag_ly_24.png', 'flag_ly_240.png', 'OK'),
    (127, 'LIE', 'LI', 'Lichtenštajnsko', 'Lichtenštajnsko', NULL, 'Lichtenštajnské kniežatstvo', 'flag_li_24.png', 'flag_li_240.png', 'OK'),
    (128, 'LTU', 'LT', 'Litva', 'Lithuania', NULL, 'Litovská republika', 'flag_lt_24.png', 'flag_lt_240.png', 'OK'),
    (129, 'LVA', 'LV', 'Lotyšsko', 'Latvia', NULL, 'Lotyšská republika', 'flag_lv_24.png', 'flag_lv_240.png', 'OK'),
    (130, 'LUX', 'LU', 'Luxembursko', 'Luxembursko', NULL, 'Luxemburské veľkovojvodstvo', 'flag_lu_24.png', 'flag_lu_240.png', 'OK'),
    (131, 'MAC', 'MO', 'Macao', 'Macao', NULL, 'Macao, Špeciàlna administratívna oblasŦ', 'flag_mo_24.png', 'flag_mo_240.png', 'OK'),
    (132, 'MDG', 'MG', 'Madagaskar', 'Madagascar', NULL, 'Madagaskarská republika', 'flag_mg_24.png', 'flag_mg_240.png', 'OK'),
    (133, 'HUN', 'HU', 'Maďarsko', 'Hungary', NULL, 'Maďarsko', 'flag_hu_24.png', 'flag_hu_240.png', 'OK'),
    (134, 'MYS', 'MY', 'Malajzia', 'Malaysia', NULL, 'Malajzia', 'flag_my_24.png', 'flag_my_240.png', 'OK'),
    (135, 'MWI', 'MW', 'Malawi', 'Malawi', NULL, 'Malawijská republika', 'flag_mw_24.png', 'flag_mw_240.png', 'OK'),
    (136, 'MDV', 'MV', 'Maldivy', 'Maldivy', NULL, 'Maldivská republika', 'flag_mv_24.png', 'flag_mv_240.png', 'OK'),
    (137, 'MLI', 'ML', 'Mali', 'Mali', NULL, 'Malijská republika', 'flag_ml_24.png', 'flag_ml_240.png', 'OK'),
    (138, 'MLT', 'MT', 'Malta', 'Malta', NULL, 'Maltská republika', 'flag_mt_24.png', 'flag_mt_240.png', 'OK'),
    (139, 'IMN', 'IM', 'Man', 'Man', NULL, 'Ostrov Man', 'flag_im_24.png', 'flag_im_240.png', 'OK'),
    (140, 'MAR', 'MA', 'Maroko', 'Morocco', NULL, 'Marocké kniežatstvo', 'flag_ma_24.png', 'flag_ma_240.png', 'OK'),
    (141, 'MHL', 'MH', 'Marshallove ostrovy', 'Marshallove ostrovy', NULL, 'Republika Marshallových ostrovov', 'flag_mh_24.png', 'flag_mh_240.png', 'OK'),
    (142, 'MTQ', 'MQ', 'Martinik', 'Martinik', NULL, 'Martinique', 'flag_mq_24.png', 'flag_mq_240.png', 'OK'),
    (143, 'MUS', 'MU', 'Maurícius', 'Maurícius', NULL, 'Maurícijská republika', 'flag_mu_24.png', 'flag_mu_240.png', 'OK'),
    (144, 'MRT', 'MR', 'Mauritánia', 'Mauritánia', NULL, 'Mauritánska islamská republika', 'flag_mr_24.png', 'flag_mr_240.png', 'OK'),
    (145, 'MYT', 'YT', 'Mayotte', 'Mayotte', NULL, 'Department Mayotte', 'flag_yt_24.png', 'flag_yt_240.png', 'OK'),
    (146, 'UMI', 'UM', 'Menšie odľahlé ostrovy USA', 'Menšie odľahlé ostrovy USA', NULL, 'Menšie odľahlé ostrovy Spjoených štátov', 'flag_um_24.png', 'flag_um_240.png', 'OK'),
    (147, 'MEX', 'MX', 'Mexiko', 'Mexico', NULL, 'Spojené štášy mexické', 'flag_mx_24.png', 'flag_mx_240.png', 'OK'),
    (148, 'FSM', 'FM', 'Mikronézia', 'Mikronézia', NULL, 'Mikronézske federatívne štáty', 'flag_fm_24.png', 'flag_fm_240.png', 'OK'),
    (149, 'MMR', 'MM', 'Mjanmarsko', 'Myanmar', NULL, 'Mjanmarská zväzová republika', 'flag_mm_24.png', 'flag_mm_240.png', 'OK'),
    (150, 'MDA', 'MD', 'Moldavsko', 'Moldavsko', NULL, 'Moldavská republika', 'flag_md_24.png', 'flag_md_240.png', 'OK'),
    (151, 'MCO', 'MC', 'Monako', 'Monako', NULL, 'Monacké kniežatstvo', 'flag_mc_24.png', 'flag_mc_240.png', 'OK'),
    (152, 'MNG', 'MN', 'Mongolsko', 'Mongolia', NULL, 'Mongolsko', 'flag_mn_24.png', 'flag_mn_240.png', 'OK'),
    (153, 'MSR', 'MS', 'Montserrat', 'Montserrat', NULL, 'Montserrat', 'flag_ms_24.png', 'flag_ms_240.png', 'OK'),
    (154, 'MOZ', 'MZ', 'Mozambik', 'Mozambique', NULL, 'Mozambická republika', 'flag_mz_24.png', 'flag_mz_240.png', 'OK'),
    (155, 'NAM', 'NA', 'Namíbia', 'Namibia', NULL, 'Namíbijská republika', 'flag_na_24.png', 'flag_na_240.png', 'OK'),
    (156, 'NRU', 'NR', 'Nauru', 'Nauru', NULL, 'Naurská republika', 'flag_nr_24.png', 'flag_nr_240.png', 'OK'),
    (157, 'DEU', 'DE', 'Nemecko', 'Germany', NULL, 'Nemecká spolková republika', 'flag_de_24.png', 'flag_de_240.png', 'OK'),
    (158, 'NPL', 'NP', 'Nepál', 'Nepal', NULL, 'Nepálska federatívna demokratická republika', 'flag_np_24.png', 'flag_np_240.png', 'OK'),
    (159, 'NER', 'NE', 'Niger', 'Niger', NULL, 'Nigérská republika', 'flag_ne_24.png', 'flag_ne_240.png', 'OK'),
    (160, 'NGA', 'NG', 'Nigéria', 'Nigeria', NULL, 'Nigérijská federatívna republika', 'flag_ng_24.png', 'flag_ng_240.png', 'OK'),
    (161, 'NIC', 'NI', 'Nikaragua', 'Nikaragua', NULL, 'Nikaragujská republika', 'flag_ni_24.png', 'flag_ni_240.png', 'OK'),
    (162, 'NIU', 'NU', 'Niue', 'Niue', NULL, 'Niue', 'flag_nu_24.png', 'flag_nu_240.png', 'OK'),
    (163, 'NFK', 'NF', 'Norfolk', 'Norfolk', NULL, 'Teritórium ostrova Norfolk', 'flag_nf_24.png', 'flag_nf_240.png', 'OK'),
    (164, 'NOR', 'NO', 'Nórsko', 'Norway', NULL, 'Nórske kráľovstvo', 'flag_no_24.png', 'flag_no_240.png', 'OK'),
    (165, 'NCL', 'NC', 'Nová Kaledónia', 'Nová Kaledónia', NULL, 'Nová Kaledónia', 'flag_nc_24.png', 'flag_nc_240.png', 'OK'),
    (166, 'NZL', 'NZ', 'Nový Zéland', 'New Zealand', NULL, 'Nový Zéland', 'flag_nz_24.png', 'flag_nz_240.png', 'OK'),
    (167, 'OMN', 'OM', 'Omán', 'Omán', NULL, 'Ománsky sultanát', 'flag_om_24.png', 'flag_om_240.png', 'OK'),
    (168, 'PAK', 'PK', 'Pakistan', 'Pakistan', NULL, 'Pakistanská islamská republika', 'flag_pk_24.png', 'flag_pk_240.png', 'OK'),
    (169, 'PLW', 'PW', 'Palau', 'Palau', NULL, 'Palauská republika', 'flag_pw_24.png', 'flag_pw_240.png', 'OK'),
    (170, 'PSE', 'PS', 'Palestína', 'Palestinian Territories', NULL, 'Palestínsky štát', 'flag_ps_24.png', 'flag_ps_240.png', 'OK'),
    (171, 'PAN', 'PA', 'Panama', 'Panama', NULL, 'Panamská republika', 'flag_pa_24.png', 'flag_pa_240.png', 'OK'),
    (172, 'VGB', 'VG', 'Britské Panenské ostrovy', 'Britské Panenské ostrovy', NULL, 'Panenské ostrovy', 'flag_vg_24.png', 'flag_vg_240.png', 'OK'),
    (173, 'PNG', 'PG', 'Papua-Nová Guinea', 'Papua-Nová Guinea', NULL, 'Nezávislý štát Papua-Nová Guinea', 'flag_pg_24.png', 'flag_pg_240.png', 'OK'),
    (174, 'PRY', 'PY', 'Paraguaj', 'Paraguay', NULL, 'Paraguajská republika', 'flag_py_24.png', 'flag_py_240.png', 'OK'),
    (175, 'PER', 'PE', 'Peru', 'Peru', NULL, 'Peruánska republika', 'flag_pe_24.png', 'flag_pe_240.png', 'OK'),
    (176, 'PCN', 'PN', 'Pitcairnove ostrovy', 'Pitcairnove ostrovy', NULL, 'Pitcairnove ostrovy', 'flag_pn_24.png', 'flag_pn_240.png', 'OK'),
    (177, 'CIV', 'CI', 'Pobrežie Slonoviny', 'Ivory Coast', NULL, 'Republika Pobrežie Slonoviny', 'flag_ci_24.png', 'flag_ci_240.png', 'OK'),
    (178, 'POL', 'PL', 'Poľsko', 'Poland', NULL, 'Poľská republika', 'flag_pl_24.png', 'flag_pl_240.png', 'OK'),
    (179, 'PRI', 'PR', 'Portoriko', 'Portoriko', NULL, 'Portorické spoločenstvo', 'flag_pr_24.png', 'flag_pr_240.png', 'OK'),
    (180, 'PRT', 'PT', 'Portugalsko', 'Portugal', NULL, 'Portugalská republika', 'flag_pt_24.png', 'flag_pt_240.png', 'OK'),
    (181, 'AUT', 'AT', 'Rakúsko', 'Austria', NULL, 'Rakúska republika', 'flag_at_24.png', 'flag_at_240.png', 'OK'),
    (182, 'REU', 'RE', 'Réunion', 'Réunion', NULL, 'Réunionský zámorský departmán', 'flag_re_24.png', 'flag_re_240.png', 'OK'),
    (183, 'GNQ', 'GQ', 'Rovníková Guinea', 'Rovníková Guinea', NULL, 'Republika rovníkovej Guiney', 'flag_gq_24.png', 'flag_gq_240.png', 'OK'),
    (184, 'ROU', 'RO', 'Rumunsko', 'Romania', NULL, 'Rumunsko', 'flag_ro_24.png', 'flag_ro_240.png', 'OK'),
    (185, 'RUS', 'RU', 'Rusko', 'Russia', NULL, 'Ruská federácia', 'flag_ru_24.png', 'flag_ru_240.png', 'OK'),
    (186, 'RWA', 'RW', 'Rwanda', 'Rwanda', NULL, 'Rwandská republika', 'flag_rw_24.png', 'flag_rw_240.png', 'OK'),
    (187, 'SPM', 'PM', 'Saint Pierre a Miquelon', 'Saint Pierre a Miquelon', NULL, 'Ostrovy Saint Pierre a Miquelon', 'flag_pm_24.png', 'flag_pm_240.png', 'OK'),
    (188, 'MAF', 'MF', 'Saint-Martin', 'Saint-Martin', NULL, 'Saint-Martin', 'flag_mf_24.png', 'flag_mf_240.png', 'OK'),
    (189, 'SLB', 'SB', 'Šalamúnove ostrovy', 'Šalamúnove ostrovy', NULL, 'Salomonove ostrovy', 'flag_sb_24.png', 'flag_sb_240.png', 'OK'),
    (190, 'SLV', 'SV', 'Salvádor', 'Salvádor', NULL, 'Salvádorská republika', 'flag_sv_24.png', 'flag_sv_240.png', 'OK'),
    (191, 'WSM', 'WS', 'Samoa', 'Samoa', NULL, 'Nezávislý štátSamoa', 'flag_ws_24.png', 'flag_ws_240.png', 'OK'),
    (192, 'SMR', 'SM', 'San Maríno', 'San Maríno', NULL, 'Sanmarínska republika', 'flag_sm_24.png', 'flag_sm_240.png', 'OK'),
    (193, 'SAU', 'SA', 'Saudská Arábia', 'Saudi Arabia', NULL, 'Saudskoarabské kráľovstvo', 'flag_sa_24.png', 'flag_sa_240.png', 'OK'),
    (194, 'SEN', 'SN', 'Senegal', 'Senegal', NULL, 'Senegalská republika', 'flag_sn_24.png', 'flag_sn_240.png', 'OK'),
    (195, 'GB-NIR', 'GB-NIR', 'Severné Írsko', 'Northern Ireland', NULL, 'Severné Írsko', 'flag_gb-nir_24.png', 'flag_gb-nir_240.png', 'OK'),
    (196, 'MKD', 'MK', 'Severné Macedónsko', 'Severné Macedónsko', NULL, 'Severomacedónska republika', 'flag_mk_24.png', 'flag_mk_240.png', 'OK'),
    (197, 'MNP', 'MP', 'Severné Mariány', 'Severné Mariány', NULL, 'Spoločenstvo ostrovov Severné Mariány', 'flag_mp_24.png', 'flag_mp_240.png', 'OK'),
    (198, 'SYC', 'SC', 'Seychely', 'Seychely', NULL, 'Seychelská republika', 'flag_sc_24.png', 'flag_sc_240.png', 'OK'),
    (199, 'SLE', 'SL', 'Sierra Leone', 'Sierra Leone', NULL, 'Sierraleonská republika', 'flag_sl_24.png', 'flag_sl_240.png', 'OK'),
    (200, 'SGP', 'SG', 'Singapur', 'Singapore', NULL, 'Singapurská republika', 'flag_sg_24.png', 'flag_sg_240.png', 'OK'),
    (201, 'SXM', 'SX', 'Sint Maarten', 'Sint Maarten', NULL, 'Sint Maarten', 'flag_sx_24.png', 'flag_sx_240.png', 'OK'),
    (202, 'SVK', 'SK', 'Slovensko', 'Slovakia', NULL, 'Slovenská republika', 'flag_sk_24.png', 'flag_sk_240.png', 'OK'),
    (203, 'SVN', 'SI', 'Slovinsko', 'Slovenia', NULL, 'Slovinská republika', 'flag_si_24.png', 'flag_si_240.png', 'OK'),
    (204, 'SOM', 'SO', 'Somálsko', 'Somalia', NULL, 'Somálska federatívna republika', 'flag_so_24.png', 'flag_so_240.png', 'OK'),
    (205, 'ARE', 'AE', 'Spojené arabské emiráty', 'Spojené arabské emiráty', NULL, 'Spojené arabské emiráty', 'flag_ae_24.png', 'flag_ae_240.png', 'OK'),
    (206, 'USA', 'US', 'Spojené štáty', 'United States', NULL, 'Spojené štáty Americké', 'flag_us_24.png', 'flag_us_240.png', 'OK'),
    (207, 'SRB', 'RS', 'Srbsko', 'Serbia', NULL, 'Srbská republika', 'flag_rs_24.png', 'flag_rs_240.png', 'OK'),
    (208, 'LKA', 'LK', 'Srí Lanka', 'Sri Lanka', NULL, 'Srílanská demokratická socialistická republika', 'flag_lk_24.png', 'flag_lk_240.png', 'OK'),
    (209, 'CAF', 'CF', 'Stredoafrická republika', 'Stredoafrická republika', NULL, 'Stredoafrická republika', 'flag_cf_24.png', 'flag_cf_240.png', 'OK'),
    (210, 'SDN', 'SD', 'Sudán', 'Sudan', NULL, 'Sudánska republika', 'flag_sd_24.png', 'flag_sd_240.png', 'OK'),
    (211, 'SUR', 'SR', 'Surinam', 'Surinam', NULL, 'Surinamská republika', 'flag_sr_24.png', 'flag_sr_240.png', 'OK'),
    (212, 'SJM', 'SJ', 'Svalbard a Jan Mayen', 'Svalbard a Jan Mayen', NULL, 'Svalbard a Jan Mayen', 'flag_sj_24.png', 'flag_sj_240.png', 'OK'),
    (213, 'SWZ', 'SZ', 'Svazijsko', 'Svazijsko', NULL, 'Svazijské kráľovstvo', 'flag_sz_24.png', 'flag_sz_240.png', 'OK'),
    (214, 'SHN', 'SH', 'Svätá Helena', 'Svätá Helena', NULL, 'Svätá Helena (zámorské územie)', 'flag_sh_24.png', 'flag_sh_240.png', 'OK'),
    (215, 'LCA', 'LC', 'Svätá Lucia', 'Svätá Lucia', NULL, 'Svätá Lucia', 'flag_lc_24.png', 'flag_lc_240.png', 'OK'),
    (216, 'BLM', 'BL', 'Svätý Bartolomej', 'Svätý Bartolomej', NULL, 'Svätý Bartolomej', 'flag_bl_24.png', 'flag_bl_240.png', 'OK'),
    (217, 'KNA', 'KN', 'Svätý Krištof a Nevis', 'Svätý Krištof a Nevis', NULL, 'Feder໡cia Svätého Krištofa a Nevisu', 'flag_kn_24.png', 'flag_kn_240.png', 'OK'),
    (218, 'STP', 'ST', 'Svätý Tomáš a Princov ostrov', 'Svätý Tomáš a Princov ostrov', NULL, 'Demokratická republika Svätého Tomáša A princovho ostrova', 'flag_st_24.png', 'flag_st_240.png', 'OK'),
    (219, 'VCT', 'VC', 'Svätý Vincent a Grenadíny', 'Svätý Vincent a Grenadíny', NULL, 'Svätý Vincent a Grenadíny', 'flag_vc_24.png', 'flag_vc_240.png', 'OK'),
    (220, 'SYR', 'SY', 'Sýria', 'Syria', NULL, 'Sýrska arabská republika', 'flag_sy_24.png', 'flag_sy_240.png', 'OK'),
    (221, 'GB-SCT', 'GB-SCT', 'Škótsko', 'Scotland', NULL, 'Škótsko', 'flag_gb-sct_24.png', 'flag_gb-sct_240.png', 'OK'),
    (222, 'ESP', 'ES', 'Španielsko', 'Spain', NULL, 'Španielske kráľovstvo', 'flag_es_24.png', 'flag_es_240.png', 'OK'),
    (223, 'CHE', 'CH', 'Švajčiarsko', 'Switzerland', NULL, 'Švajčiarska konfederácia', 'flag_ch_24.png', 'flag_ch_240.png', 'OK'),
    (224, 'SWE', 'SE', 'Švédsko', 'Sweden', NULL, 'Švédske kráľovstvo', 'flag_se_24.png', 'flag_se_240.png', 'OK'),
    (225, 'TJK', 'TJ', 'Tadžikistan', 'Tadžikistan', NULL, 'Taǆická republika', 'flag_tj_24.png', 'flag_tj_240.png', 'OK'),
    (226, 'TWN', 'TW', 'Taiwan', 'Taiwan', NULL, 'Čínska republika', 'flag_tw_24.png', 'flag_tw_240.png', 'OK'),
    (227, 'ITA', 'IT', 'Taliansko', 'Italy', NULL, 'Talianska republika', 'flag_it_24.png', 'flag_it_240.png', 'OK'),
    (228, 'TZA', 'TZ', 'Tanzánia', 'Tanzania', NULL, 'Tanzánijská zjednotená republika', 'flag_tz_24.png', 'flag_tz_240.png', 'OK'),
    (229, 'THA', 'TH', 'Thajsko', 'Thailand', NULL, 'Thajské kráľovstvo', 'flag_th_24.png', 'flag_th_240.png', 'OK'),
    (230, 'TGO', 'TG', 'Togo', 'Togo', NULL, 'Togská republika', 'flag_tg_24.png', 'flag_tg_240.png', 'OK'),
    (231, 'TKL', 'TK', 'Tokelau', 'Tokelau', NULL, 'Tokelauské ostrovy', 'flag_tk_24.png', 'flag_tk_240.png', 'OK'),
    (232, 'TON', 'TO', 'Tonga', 'Tonga', NULL, 'Tongské kráľovstvo', 'flag_to_24.png', 'flag_to_240.png', 'OK'),
    (233, 'TTO', 'TT', 'Trinidad a Tobago', 'Trinidad a Tobago', NULL, 'Republika Trinidad a Tobaga', 'flag_tt_24.png', 'flag_tt_240.png', 'OK'),
    (234, 'TUN', 'TN', 'Tunisko', 'Tunisia', NULL, 'Tuniská republika', 'flag_tn_24.png', 'flag_tn_240.png', 'OK'),
    (235, 'TUR', 'TR', 'Turecko', 'Turkey', NULL, 'Turecká republika', 'flag_tr_24.png', 'flag_tr_240.png', 'OK'),
    (236, 'TKM', 'TM', 'Turkménsko', 'Turkménsko', NULL, 'Turkménsko', 'flag_tm_24.png', 'flag_tm_240.png', 'OK'),
    (237, 'TCA', 'TC', 'Turks a Caicos', 'Turks a Caicos', NULL, 'Ostrovy Turks a Caicos', 'flag_tc_24.png', 'flag_tc_240.png', 'OK'),
    (238, 'TUV', 'TV', 'Tuvalu', 'Tuvalu', NULL, 'Tuvalu', 'flag_tv_24.png', 'flag_tv_240.png', 'OK'),
    (239, 'UGA', 'UG', 'Uganda', 'Uganda', NULL, 'Ugandská republika', 'flag_ug_24.png', 'flag_ug_240.png', 'OK'),
    (240, 'UKR', 'UA', 'Ukrajina', 'Ukraine', NULL, 'Ukrajina', 'flag_ua_24.png', 'flag_ua_240.png', 'OK'),
    (241, 'URY', 'UY', 'Uruguaj', 'Uruguay', NULL, 'Uruguajská východná republika', 'flag_uy_24.png', 'flag_uy_240.png', 'OK'),
    (242, 'UZB', 'UZ', 'Uzbekistan', 'Uzbekistan', NULL, 'Uzbecká republika', 'flag_uz_24.png', 'flag_uz_240.png', 'OK'),
    (243, 'VUT', 'VU', 'Vanuatu', 'Vanuatu', NULL, 'Vanuatská republika', 'flag_vu_24.png', 'flag_vu_240.png', 'OK'),
    (244, 'VAT', 'VA', 'Vatikán', 'Vatikán', NULL, 'Svätá stolica (Vatikánsky mestský štát', 'flag_va_24.png', 'flag_va_240.png', 'OK'),
    (245, 'GBR', 'GB', 'Spojené kráľovstvo', 'United Kingdom', NULL, 'Spojené kráľovstvo Veľkej Británie a SevernéhoÌrska', 'flag_gb_24.png', 'flag_gb_240.png', 'OK'),
    (246, 'VEN', 'VE', 'Venezuela', 'Venezuela', NULL, 'Venezuelská bolívarovská republika', 'flag_ve_24.png', 'flag_ve_240.png', 'OK'),
    (247, 'CXR', 'CX', 'Vianočný ostrov', 'Vianočný ostrov', NULL, 'Teritórium Vianočného ostrova', 'flag_cx_24.png', 'flag_cx_240.png', 'OK'),
    (248, 'VNM', 'VN', 'Vietnam', 'Vietnam', NULL, 'Vietnamská socialistická republika', 'flag_vn_24.png', 'flag_vn_240.png', 'OK'),
    (249, 'TLS', 'TL', 'Východný Timor', 'Východný Timor', NULL, 'Východotimorská demokratická republika', 'flag_tl_24.png', 'flag_tl_240.png', 'OK'),
    (250, 'GB-WLS', 'GB-WLS', 'Wales', 'Wales', NULL, 'Wales', 'flag_gb-wls_24.png', 'flag_gb-wls_240.png', 'OK'),
    (251, 'WLF', 'WF', 'Wallis a Futuna', 'Wallis a Futuna', NULL, 'Teritórium ostrovov Wallis a Futuna', 'flag_wf_24.png', 'flag_wf_240.png', 'OK'),
    (252, 'ZMB', 'ZM', 'Zambia', 'Zambia', NULL, 'Zambijská republika', 'flag_zm_24.png', 'flag_zm_240.png', 'OK'),
    (253, 'ESH', 'EH', 'Západná Sahara', 'Západná Sahara', NULL, 'Západná Sahara', 'flag_eh_24.png', 'flag_eh_240.png', 'OK'),
    (254, 'ZWE', 'ZW', 'Zimbabwe', 'Zimbabwe', NULL, 'Zimbabwianska republika', 'flag_zw_24.png', 'flag_zw_240.png', 'OK');

-- 4. Doplnit sportove kody FIFA / IIHF / UEFA.
UPDATE admin.countries c SET
    sport_code_fifa = s.fifa,
    sport_code_iihf = s.iihf,
    sport_code_uefa = s.uefa
FROM (VALUES
('ALB', NULL, NULL, 'ALB'),
    ('AND', NULL, NULL, 'AND'),
    ('ARG', 'ARG', NULL, NULL),
    ('ARM', NULL, NULL, 'ARM'),
    ('AUS', 'AUS', NULL, NULL),
    ('AUT', 'AUT', 'AUT', 'AUT'),
    ('AZE', NULL, NULL, 'AZE'),
    ('BEL', 'BEL', NULL, 'BEL'),
    ('BGR', NULL, NULL, 'BUL'),
    ('BIH', 'BIH', NULL, 'BIH'),
    ('BLR', NULL, NULL, 'BLR'),
    ('BRA', 'BRA', NULL, NULL),
    ('CAN', 'CAN', 'CAN', NULL),
    ('CHE', 'SUI', 'SUI', 'SUI'),
    ('CIV', 'CIV', NULL, NULL),
    ('COD', 'COD', NULL, NULL),
    ('COL', 'COL', NULL, NULL),
    ('CPV', 'CPV', NULL, NULL),
    ('CUW', 'CUW', NULL, NULL),
    ('CYP', NULL, NULL, 'CYP'),
    ('CZE', 'CZE', 'CZE', 'CZE'),
    ('DEU', 'GER', 'GER', 'GER'),
    ('DNK', NULL, 'DEN', 'DEN'),
    ('DZA', 'ALG', NULL, NULL),
    ('ECU', 'ECU', NULL, NULL),
    ('EGY', 'EGY', NULL, NULL),
    ('ESP', 'ESP', NULL, 'ESP'),
    ('EST', NULL, NULL, 'EST'),
    ('FIN', NULL, 'FIN', 'FIN'),
    ('FRA', 'FRA', NULL, 'FRA'),
    ('FRO', NULL, NULL, 'FRO'),
    ('GB-ENG', 'ENG', NULL, 'ENG'),
    ('GB-NIR', NULL, NULL, 'NIR'),
    ('GB-SCT', 'SCO', NULL, 'SCO'),
    ('GB-WLS', NULL, NULL, 'WAL'),
    ('GBR', NULL, 'GBR', NULL),
    ('GEO', NULL, NULL, 'GEO'),
    ('GHA', 'GHA', NULL, NULL),
    ('GIB', NULL, NULL, 'GIB'),
    ('GRC', NULL, NULL, 'GRE'),
    ('HRV', 'CRO', NULL, 'CRO'),
    ('HTI', 'HAI', NULL, NULL),
    ('HUN', NULL, 'HUN', 'HUN'),
    ('IRL', NULL, NULL, 'IRL'),
    ('IRN', 'IRN', NULL, NULL),
    ('IRQ', 'IRQ', NULL, NULL),
    ('ISL', NULL, NULL, 'ISL'),
    ('ISR', NULL, NULL, 'ISR'),
    ('ITA', NULL, 'ITA', 'ITA'),
    ('JOR', 'JOR', NULL, NULL),
    ('JPN', 'JPN', NULL, NULL),
    ('KAZ', NULL, NULL, 'KAZ'),
    ('KOR', 'KOR', NULL, NULL),
    ('LTU', NULL, NULL, 'LTU'),
    ('LUX', NULL, NULL, 'LUX'),
    ('LVA', NULL, 'LAT', 'LVA'),
    ('MAR', 'MAR', NULL, NULL),
    ('MDA', NULL, NULL, 'MDA'),
    ('MEX', 'MEX', NULL, NULL),
    ('MKD', NULL, NULL, 'MKD'),
    ('MLT', NULL, NULL, 'MLT'),
    ('MNE', NULL, NULL, 'MNE'),
    ('NLD', 'NED', NULL, 'NED'),
    ('NOR', 'NOR', 'NOR', 'NOR'),
    ('NZL', 'NZL', NULL, NULL),
    ('PAN', 'PAN', NULL, NULL),
    ('POL', NULL, NULL, 'POL'),
    ('PRT', 'POR', NULL, 'POR'),
    ('PRY', 'PAR', NULL, NULL),
    ('QAT', 'QAT', NULL, NULL),
    ('ROU', NULL, NULL, 'ROU'),
    ('SAU', 'KSA', NULL, NULL),
    ('SEN', 'SEN', NULL, NULL),
    ('SMR', NULL, NULL, 'SMR'),
    ('SRB', NULL, NULL, 'SRB'),
    ('SVK', NULL, 'SVK', 'SVK'),
    ('SVN', NULL, 'SLO', 'SVN'),
    ('SWE', 'SWE', 'SWE', 'SWE'),
    ('TUN', 'TUN', NULL, NULL),
    ('TUR', 'TUR', NULL, 'TUR'),
    ('UKR', NULL, NULL, 'UKR'),
    ('UNK', NULL, NULL, 'KOS'),
    ('URY', 'URU', NULL, NULL),
    ('USA', 'USA', 'USA', NULL),
    ('UZB', 'UZB', NULL, NULL),
    ('ZAF', 'RSA', NULL, NULL)
) AS s(iso, fifa, iihf, uefa)
WHERE c.country_code = s.iso;

-- 5. Premapovat UCL kluby zo sportovych kodov UEFA na ISO kody.
UPDATE "lm2026-27".teams t
SET country_code = c.country_code
FROM admin.countries c
WHERE c.sport_code_uefa = t.country_code
  AND t.country_code IS DISTINCT FROM c.country_code;

-- 6. Overit, ze kazdy klub ma platny kod; inak transakciu zrusit.
DO $$
DECLARE bad_count INTEGER; bad_list TEXT;
BEGIN
    SELECT COUNT(*), string_agg(DISTINCT t.country_code, ', ')
      INTO bad_count, bad_list
      FROM "lm2026-27".teams t
     WHERE t.country_code IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM admin.countries c WHERE c.country_code = t.country_code);
    IF bad_count > 0 THEN
        RAISE EXCEPTION 'Import zruseny: % klubov ma neplatny kod statu (%)', bad_count, bad_list;
    END IF;
END $$;

-- 7. Znova napojit FK, uz iba na spolocny admin.countries.
ALTER TABLE "lm2026-27".teams
    ADD CONSTRAINT ucl_teams_admin_country_code_fkey
    FOREIGN KEY (country_code) REFERENCES admin.countries(country_code);

-- 8. Stary UCL ciselnik statov nahradil admin.countries, uz sa nepouziva.
DROP TABLE IF EXISTS "lm2026-27".countries;

INSERT INTO admin.schema_versions (version, description)
VALUES (54, 'Import 254 statov z CSV, sportove kody a premapovanie UCL klubov na ISO')
ON CONFLICT (version) DO NOTHING;

COMMIT;
